### ISSUE TITLE
Shard7's reconnect code isn't in here yet? :)

### ISSUE THREAD

**Issue by savraj** [asynclabs/WiShield_user_contrib#2]
I just found the Shard7 reconnect code, can't wait to try it today... But why isn't it in the user contrib branch yet? :)

**Comment by GregEigsti** [comment]
I don't use WiServer and my time for this is limited - so I have added the bug fixes and features that interest me the most.  The WiServer fixes (reconnect code) are not absolute; that is they work for some folks but not others - at this point the author does not appear to be working on WiServer - he is in the same boat as I - prioritization of his limited time has left WiServer in the hands of the community and so far nobody had championed the cause...

BTW - I believe that WiServer is kinda/sorta/mostly broken in this branch and I have been considering removing it altogether.  Weird thing is that curl successfully retrieves a page from WiServer but a browser does not (have tried Safari on Mac OSX).  I think the break is related to the most recent bug fix checkin but am not completely sure - the fix was for the too large of a packet issue (one of the latest, if not the latest, fixes).

If you want to test it out I'd be happy to work with you to keep WiServer maintained.

I'm hoping to get some time this weekend to get the UDP fix mentioned by RRyan into the user contrib branch.  Does not take long to code it up but testing is a big time hit.

**Comment by GregEigsti** [comment]
I was correct - WiServer (SimpleServer) as well as WebServer were broken due to the "fix" that I mentioned.  I'll be reverting that "fix" today - so the user contrib stack should become much better behaved.
